name: XCS330
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - cloudpickle=3.0.0
  - cycler=0.11.0
  - h5py=3.12.1
  - lockfile=0.12.2
  - opt-einsum=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pickleshare=0.7.5
  - python-dateutil=2.9.0.post0
  - requests=2.32.3
  - scipy=1.15.1
  - six=1.16.0
  - scikit-learn=1.6.1
  - tensorboard=2.18.0
  - pytest=7.4.4
  - imageio=2.37.0
  - svglib=1.5.1
  - matplotlib=3.10.0
  - pip=25.0
  - pip:
    - googledrivedownloader==1.1.0
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch"
    - torch==2.5.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.5.1+cpu; sys_platform == "linux" or sys_platform == "win32"
    - rouge-score==0.1.2
    # Manage the below packages over pip to avoid segmentation fault in transformers on Mac
    - huggingface-hub==0.28.0
    - transformers==4.48.1
    - datasets==3.2.0
    - numpy==2.2.2
